source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "jekyll-include-cache"
gem "webrick" # required for Ruby 3.x+
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
